apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: buffer
  name: session-service-1
  labels:
    app: session-service
    version: '1'
    track: stable
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: session-service
        version: '1'
        track: stable
    spec:
      containers:
      - name: session-service
        image: bufferapp/session-service:beta-6
        ports:
        - containerPort: 80
        env:
        - name: RELEASE_TRACK
          value: stable
        - name: JWT_SECRET
          value: beta-secret
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              key: redis-uri
              name: buffer-session-service-keys
        - name: BUGSNAG_KEY
          valueFrom:
            secretKeyRef:
              key: bugsnag
              name: buffer-session-service-keys
        livenessProbe:
          httpGet:
            path: /health-check
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 150Mi
      imagePullSecrets:
        - name: dhbufferapp
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: session-service-1
  namespace: buffer
  labels:
    app: session-service
    version: '1'
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: session-service
    version: '1'
